### Get root
GET http://localhost:3000

### Register
POST http://localhost:3000/v1/register
Content-Type: application/json

{
    "email":"demo@gmail.com",
    "password": "admin123"
}

### Login
POST http://localhost:3000/v1/login
Content-Type: application/json

{
    "email":"demo@gmail.com",
    "password": "admin123"
}


#### Get notes
GET http://localhost:3000/v1/notes
Content-Type: application/json
session-id: cm3126u8h00029uqh48avmfrk

### Create note

POST http://localhost:3000/v1/notes
Content-Type: application/json
session-id: cm3126u8h00029uqh48avmfrk

{
    "content": "TestNote"
}


### Get post detail
GET http://localhost:3000/posts/akoj
