### Get root
GET http://localhost:3000

### Register
POST http://localhost:3000/v1/register
Content-Type: application/json

{
    "email":"demo@gmail.com",
    "password": "admin123",
    "name": "Demo Account"
}

### Login
POST http://localhost:3000/v1/login
Content-Type: application/json

{
    "email":"demo@gmail.com",
    "password": "admin123"
}


#### Get notes
GET http://localhost:3000/v1/notes
Content-Type: application/json
session-id: cm35mt0wo0000hera20huzwha


### Create note
POST http://localhost:3000/v1/notes
Content-Type: application/json
session-id: cm35m5lo20000fd97c8a1wlnt

{
    "content": "Music + Lofi + Coffee + Rain #cozy #coffee https://www.youtube.com/watch?v=2fQyuhzfBYk",
    "isPrivate": true
}


### Delete note
DELETE http://localhost:3000/v1/notes/cm35m5te10002fd97v2qce35o
session-id: cm35m5lo20000fd97c8a1wlnt
